version: '3'
services:
  db:
    build: ./db2
    privileged: true
    environment:
      LICENSE: accept
      DB2INST1_PASSWORD: thisisthepwd
      DB2INSTANCE: db2inst1
      DBNAME: testdb
    command: su - db2inst1 -c "db2start"
    ports:
      - 50000:50000
    volumes:
      - db-data:/database
volumes:
  db-data:
